<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BenchmarkDotNet" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\EventScope.Core\EventScope.Core.csproj" />
    <ProjectReference Include="..\..\src\EventScope.Storage\EventScope.Storage.csproj" />
  </ItemGroup>

</Project>
